sudo: required

language: python

python:
  - "3.9.10"

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - python -m unittest etlstat/database/test/test_mysql.py
  - python -m unittest etlstat/extractor/test/test_extractor.py
  - python -m unittest etlstat/text/test/test_utils.py
  - pylint --errors-only --rcfile .pylintrc etlstat
